### PR TITLE
Update ContextMenu_CN.txt

### PR DESCRIPTION
**Pull request by iamming611**
This is my first time to use github, hope I didn't mess up anything.
I have translated ContextMenu_CN
Please check it out :)

### CODE REVIEW

**Comment by quarantin** [comment]
Hi! Thank you for taking the time to help with translations! Your previous pull request was OK, but this one I'm not sure why you have many changes, not just the ContextMenu_CN.txt. Could you try to clone again the repo to another location, just copy the ContextMenu_CN.txt in the new location, and create a new pull request?
If you don't feel like doing it, I can manage but then you would not appear as the author of the pull request. Whatever you decide. I can guide you if you need help.

**Comment by iamming611** [comment]
Can I just paste the translated words here so you can copy and paste maunally into your file?

	ContextMenu_AddSpearToGrave = "插上长矛"
	ContextMenu_RemoveSpearFromGrave = "移除长矛"

**Comment by iamming611** [comment]
Sorry about the mess, because the first submission of ContextMenu.txt, I accidentally add an extra "e" there, so I submitted it again which caused the confusion

**Comment by quarantin** [comment]
No worries, of course I can do it :+1:

**Comment by quarantin** [comment]
So I'm closing this pull-request. Thanks again man!

**Comment by quarantin** [comment]
@iamming611 Hey is it simplified or traditional Chinese?
Could you provide both please?

**Comment by quarantin** [comment]
@iamming611 I changed the english version for Sandbox_SpearTraps_SpearTrapsKillPlayer_tooltip. If you don't mind updating the translation.

**Comment by quarantin** [comment]
Hey hi, sorry for the late answer. I can't find the new translation on any of your branches, where did you put it?

**Pull request closed without merging**
